version: '3.8'

services:
  bot:
    build: .
    container_name: stock-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs  # If you want to persist logs 